import { Router } from 'express';
import { execSync } from 'child_process';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.SUPABASE_URL || 'http://127.0.0.1:54321',
  process.env.SUPABASE_SERVICE_ROLE_KEY || '',
);

export const gitRouter = Router();

function run(cmd: string, cwd: string): string {
  return execSync(cmd, { cwd, encoding: 'utf-8', timeout: 30000 }).trim();
}

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').substring(0, 50);
}

// Commit changes
gitRouter.post('/api/git/commit', async (req, res) => {
  const { jobId, localPath } = req.body;

  try {
    const { data: job } = await supabase.from('jobs').select('*, tasks(title, type)').eq('id', jobId).single();
    if (!job) return res.status(404).json({ error: 'Job not found' });

    const task = (job as any).tasks;
    const message = `codesync(${task.type}): ${task.title}`;

    run('git add -A', localPath);
    const sha = run(`git commit -m "${message.replace(/"/g, '\\"')}"`, localPath);

    res.json({ ok: true, sha, message });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Push to current branch
gitRouter.post('/api/git/push', async (req, res) => {
  const { localPath } = req.body;

  try {
    const output = run('git push', localPath);
    const branch = run('git branch --show-current', localPath);
    res.json({ ok: true, branch, output });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Create branch + PR
gitRouter.post('/api/git/pr', async (req, res) => {
  const { jobId, localPath } = req.body;

  try {
    const { data: job } = await supabase.from('jobs').select('*, tasks(id, title, type, description)').eq('id', jobId).single();
    if (!job) return res.status(404).json({ error: 'Job not found' });

    const task = (job as any).tasks;
    const shortId = task.id.substring(0, 8);
    const branch = `codesync/${shortId}-${slugify(task.title)}`;
    const message = `codesync(${task.type}): ${task.title}`;

    // Build PR body from phase outputs
    const phases = (job.phases_completed as any[]) || [];
    let body = `## ${task.title}\n\n${task.description || ''}\n\n`;
    body += `### Phase Outputs\n\n`;
    for (const p of phases) {
      body += `**${p.phase}** (attempt ${p.attempt})\n${typeof p.output === 'string' ? p.output.substring(0, 500) : JSON.stringify(p.output).substring(0, 500)}\n\n`;
    }
    body += `---\nGenerated by CodeSync`;

    run(`git checkout -b "${branch}"`, localPath);
    run('git add -A', localPath);
    run(`git commit -m "${message.replace(/"/g, '\\"')}"`, localPath);
    run(`git push -u origin "${branch}"`, localPath);

    const prUrl = run(`gh pr create --title "${message.replace(/"/g, '\\"')}" --body "${body.replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`, localPath);

    res.json({ ok: true, branch, prUrl });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});
