import { useCallback, useMemo } from 'react';
import { toTaskView } from '../lib/task-view';
import type { CurrentProjectWorkspaceProps, ProjectWorkspaceProps } from '../components/project-workspace-types';

export function useCurrentProjectWorkspaceProps({
  project,
  projects,
  profile,
  webNotifications,
  notifications,
  milestone,
  todoItems,
  reviewItems,
  tasks,
  activeWorkstreams,
  allWorkstreams,
  members,
  flows,
  setFlows,
  customTypes,
  jobs,
  memberMap,
  flowMap,
  typeFlowMap,
  mentionedTaskIds,
  commentCounts,
  focusTaskId,
  focusWsId,
  showTaskForm,
  taskFormWorkstream,
  editingTask,
  showAddProject,
  showMembersModal,
  onSwitchProject,
  onOpenAddProject,
  onSignOut,
  onOpenMembersModal,
  onUpdateLocalPath,
  onCloseAddProject,
  onCreateProject,
  onCloseMembersModal,
  onSaveCustomType,
  onCreateTask,
  onUpdateTaskForm,
  onCloseCreateTask,
  onCloseEditTask,
  onStartEditingTask,
  onCreateWorkstream,
  onUpdateWorkstream,
  onDeleteWorkstream,
  onSwapColumns,
  onAddTask,
  onRunWorkstream,
  onRunTask,
  onDeleteTask,
  onUpdateTask,
  onMoveTask,
  onTerminate,
  onReply,
  onApprove,
  onReject,
  onRework,
  onDeleteJob,
  onMoveToBacklog,
  onContinue,
  onCreatePr,
  onRestoreArchiveWorkstream,
  onSaveFlow,
  onSaveFlowSteps,
  onCreateFlow,
  onDeleteFlow,
  onSwapFlows,
}: CurrentProjectWorkspaceProps): ProjectWorkspaceProps {
  const handleEditTask = useCallback((taskId: string) => {
    const rawTask = tasks.find(task => task.id === taskId);
    if (!rawTask) return;

    const flowName = rawTask.flow_id
      ? flowMap[rawTask.flow_id]
      : (typeFlowMap[rawTask.type] ? flowMap[typeFlowMap[rawTask.type]] : null);

    onStartEditingTask(toTaskView(rawTask, memberMap, flowName), rawTask);
  }, [flowMap, memberMap, onStartEditingTask, tasks, typeFlowMap]);

  return useMemo(() => ({
    headerProps: {
      project,
      projects,
      user: { id: profile.id, initials: profile.initials },
      webNotifications,
      notifications,
      milestone,
      todoItems,
      reviewItems,
      onSwitchProject,
      onNewProject: onOpenAddProject,
      onSignOut,
      onManageMembers: onOpenMembersModal,
      onUpdateLocalPath,
    },
    routesProps: {
      project,
      tasks,
      jobs,
      activeWorkstreams,
      allWorkstreams,
      flows,
      setFlows,
      memberMap,
      flowMap,
      typeFlowMap,
      mentionedTaskIds,
      commentCounts,
      focusTaskId,
      focusWsId,
      userId: profile.id,
      onCreateWorkstream,
      onUpdateWorkstream,
      onDeleteWorkstream,
      onSwapColumns,
      onAddTask,
      onRunWorkstream,
      onRunTask,
      onEditTask: handleEditTask,
      onDeleteTask,
      onUpdateTask,
      onMoveTask,
      onTerminate,
      onReply,
      onApprove,
      onReject,
      onRework,
      onDeleteJob,
      onMoveToBacklog,
      onContinue,
      onCreatePr,
      onRestoreArchiveWorkstream,
      onSaveFlow,
      onSaveFlowSteps,
      onCreateFlow,
      onDeleteFlow,
      onSwapFlows,
    },
    modalProps: {
      project,
      userId: profile.id,
      activeWorkstreams,
      members,
      flows,
      customTypes,
      showTaskForm,
      taskFormWorkstream,
      editingTask,
      showAddProject,
      showMembersModal,
      onSaveCustomType,
      onCreateTask,
      onUpdateTaskForm,
      onCloseCreateTask,
      onCloseEditTask,
      onCloseAddProject,
      onCreateProject,
      onCloseMembersModal,
    },
  }), [
    activeWorkstreams,
    allWorkstreams,
    commentCounts,
    customTypes,
    editingTask,
    flowMap,
    flows,
    focusTaskId,
    focusWsId,
    handleEditTask,
    jobs,
    memberMap,
    members,
    mentionedTaskIds,
    milestone,
    notifications,
    onAddTask,
    onApprove,
    onCloseAddProject,
    onCloseCreateTask,
    onCloseEditTask,
    onCloseMembersModal,
    onContinue,
    onCreateFlow,
    onCreatePr,
    onCreateProject,
    onCreateTask,
    onCreateWorkstream,
    onDeleteFlow,
    onDeleteJob,
    onDeleteTask,
    onDeleteWorkstream,
    onMoveTask,
    onMoveToBacklog,
    onOpenAddProject,
    onOpenMembersModal,
    onReject,
    onReply,
    onRestoreArchiveWorkstream,
    onRework,
    onRunTask,
    onRunWorkstream,
    onSaveCustomType,
    onSaveFlow,
    onSaveFlowSteps,
    onSignOut,
    onSwapColumns,
    onSwapFlows,
    onSwitchProject,
    onTerminate,
    onUpdateLocalPath,
    onUpdateTask,
    onUpdateTaskForm,
    onUpdateWorkstream,
    profile.id,
    profile.initials,
    project,
    projects,
    reviewItems,
    setFlows,
    showAddProject,
    showMembersModal,
    showTaskForm,
    taskFormWorkstream,
    tasks,
    todoItems,
    typeFlowMap,
    webNotifications,
  ]);
}
